{
 "title": "External Adapters",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "adapters" },
   {
    "name": "feed",
    "query": "cache_data_get_values{namespace=\"$namespace\"}"
   },
   {
    "name": "adapter",
    "query": "http_requests_total{namespace=\"$namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu usage percent",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Heap usage MB",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=\"$namespace\",app_name=~\"$adapter.*\"} / 1000 / 1000",
     "legendFormat": "MB"
    }
   ]
  },
  {
   "title": "Http requests / minute",
   "type": "graph",
   "gridPos": { "h": 12.5, "w": 24, "x": 0, "y": 7.5 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 ",
     "legendFormat": "{{app_name}} {{feed_id}} {{status_code}} {{type}} CacheWarmer:{{is_cache_warming}}"
    }
   ]
  },
  {
   "title": "Average http request duration seconds",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])/rate(http_request_duration_seconds_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Http request duration seconds heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7.5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per type",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 6, "x": 0, "y": 27.5 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per status code",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 6, "x": 6, "y": 27.5 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per feed",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 6, "x": 12, "y": 27.5 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (feed_id)",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per cache type",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 6, "x": 18, "y": 27.5 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (is_cache_warming)",
     "legendFormat": "CacheWarmer:{{is_cache_warming}}"
    }
   ]
  },
  {
   "title": "Redis connections open",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "conn" }
   ],
   "targets": [
    {
     "expr": "redis_connections_open{namespace=\"$namespace\",app_name=~\"$adapter.*\"}",
     "legendFormat": "connections open"
    }
   ]
  },
  {
   "title": "Redis connection retries",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "retries" }
   ],
   "targets": [
    {
     "expr": "sum(redis_retries_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"})",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "Redis commands sent / minute per status",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "sent" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_sent_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 ",
     "legendFormat": "{{status}} {{function_name}}"
    }
   ]
  },
  {
   "title": "Active websocket connections",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 4, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "conn" }
   ],
   "targets": [
    {
     "expr": "ws_connection_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}",
     "legendFormat": "{{app_name}} | Key:{{key}}"
    }
   ]
  },
  {
   "title": "Websocket connection errors",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "errors" }
   ],
   "targets": [
    {
     "expr": "ws_connection_errors{namespace=\"$namespace\",app_name=~\"$adapter.*\"}",
     "legendFormat": "{{app_name}} | Key:{{key}}"
    }
   ]
  },
  {
   "title": "Websocket connection retries",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "retries" }
   ],
   "targets": [
    {
     "expr": "ws_connection_retries{namespace=\"$namespace\",app_name=~\"$adapter.*\"}",
     "legendFormat": "{{app_name}} | Key:{{key}}"
    }
   ]
  },
  {
   "title": "Active websocket subscriptions",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 0, "y": 42.5 },
   "yaxes": [
    { "format": "subs" }
   ],
   "targets": [
    {
     "expr": "ws_subscription_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}",
     "legendFormat": "{{app_name}} | ConnKey: {{ connection_key }} ConnUrl: {{ connection_url }} Feed: {{feed_id}}"
    }
   ]
  },
  {
   "title": "Websocket messages received / second",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 12, "y": 42.5 },
   "yaxes": [
    { "format": "msg/s" }
   ],
   "targets": [
    {
     "expr": "rate(ws_message_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])",
     "legendFormat": "{{app_name}} | Feed: {{feed_id}}"
    }
   ]
  },
  {
   "title": "Cached feed values",
   "type": "stat",
   "gridPos": { "h": 12.5, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_data_get_values{namespace=\"$namespace\",app_name=~\"$adapter.*\"}",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Max age per cache entry",
   "type": "bargauge",
   "gridPos": { "h": 7.5, "w": 12, "x": 0, "y": 62.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cache_data_max_age{namespace=\"$namespace\",app_name=~\"$adapter.*\"}/1000) != 0",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Staleness per cache entry",
   "type": "bargauge",
   "gridPos": { "h": 7.5, "w": 12, "x": 12, "y": 62.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cache_data_staleness_seconds{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) != 0",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Cache entry sets per second",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "set/s" }
   ],
   "targets": [
    {
     "expr": "rate(cache_data_set_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Cache entry gets per second",
   "type": "graph",
   "gridPos": { "h": 7.5, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "get/s" }
   ],
   "targets": [
    {
     "expr": "rate(cache_data_get_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])",
     "legendFormat": "{{feed_id}}"
    }
   ]
  }
 ]
}