{
 "title": "External Adapters Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "adapters" },
   {
    "name": "feed",
    "query": "cache_data_get_values{namespace=\"$namespace\"}"
   },
   {
    "name": "adapter",
    "query": "http_requests_total{namespace=\"$namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu usage percent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 100) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap usage MB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_heap_size_used_bytes{namespace=\"$namespace\",app_name=~\"$adapter.*\"} / 1000 / 1000) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per feed",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{feed_id=~\"$feed.*\",namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60) by (feed_id, service)",
     "legendFormat": "{{service}} | {{feed_id}}"
    }
   ]
  },
  {
   "title": "Average http request duration seconds per EA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (type, service)",
     "legendFormat": "{{service}} | {{type}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per status code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (status_code, service)",
     "legendFormat": "{{service}} | {{status_code}}"
    }
   ]
  },
  {
   "title": "Http requests / minute per cache type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60 )by (is_cache_warming, service)",
     "legendFormat": "{{service}} | CacheWarmer:{{is_cache_warming}}"
    }
   ]
  },
  {
   "title": "Redis connections open",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "conn" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connections_open{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Redis connection retries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 45 },
   "yaxes": [
    { "format": "retries" }
   ],
   "targets": [
    {
     "expr": "sum(redis_retries_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Redis commands sent / minute per app",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "sent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_sent_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval]) * 60) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active websocket connections per EA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "conn" }
   ],
   "targets": [
    {
     "expr": "sum(ws_connection_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Websocket connection errors per EA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "errors" }
   ],
   "targets": [
    {
     "expr": "sum(ws_connection_errors{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Websocket connection retries per EA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 45 },
   "yaxes": [
    { "format": "retries" }
   ],
   "targets": [
    {
     "expr": "sum(ws_connection_retries{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active websocket subscriptions per EA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "subs" }
   ],
   "targets": [
    {
     "expr": "sum(ws_subscription_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Websocket messages received / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ws_message_total{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cache entry sets per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "set/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_data_set_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cache entry gets per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "get/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_data_get_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}