{
 "title": "External Adapters Release",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "adapters" },
   {
    "name": "feed",
    "query": "cache_data_get_values{namespace=\"$namespace\"}"
   },
   {
    "name": "adapter",
    "query": "http_requests_total{namespace=\"$namespace\"}"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Inbound Requests (Node → EA)" },
  {
   "title": "Top 10 - 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(app_name) (rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\",status_code=~\"^5..\"}[$__rate_interval])) / sum by(app_name) (rate(http_requests_total{app_name!=\"\",namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "Top 10 - 4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(app_name) (rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\",status_code=~\"^4..\"}[$__rate_interval])) / sum by(app_name) (rate(http_requests_total{app_name!=\"\",namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "Bot 10 - (Cache Hit / Total Req Count) Ratio",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, (sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\" ,type=\"cacheHit\"}[$__rate_interval])) by (app_name) / sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\" }[$__rate_interval])) by (app_name))) * 100"
    }
   ]
  },
  {
   "title": "Top 10 - Request duration (All envs) ",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\",app_name=~\"$adapter.*\" }[$__rate_interval])/rate(http_request_duration_seconds_count{namespace=\"$namespace\",app_name=~\"$adapter.*\" }[$__rate_interval])) by (app_name))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 }, "content": "# Outbound Requests (EA → DP) " },
  {
   "title": "Provider 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\" ,provider_status_code=~\"^5..\"}[$__rate_interval])) by (app_name, provider_status_code)"
    }
   ]
  },
  {
   "title": "Provider 4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\" ,provider_status_code=~\"^4..\"}[$__rate_interval])) by (app_name, provider_status_code)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 46 }, "content": " # Adapter State" },
  {
   "title": "Top 10 - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",app_name=~\"$adapter.*\" }[5m])) by (app_name) * 100)"
    }
   ]
  },
  {
   "title": "Top 10 - Node.js Heap Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "MB" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum (nodejs_heap_size_used_bytes{namespace=\"$namespace\",app_name=~\"$adapter.*\" ,app_name!=\"REFERENCE_TRANSFORM\"} / 1000 / 1000) by (app_name))"
    }
   ]
  },
  {
   "title": "Avg - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{namespace=\"$namespace\",app_name=~\"$adapter.*\" }[5m])) * 100"
    }
   ]
  },
  {
   "title": "Avg - Node.js Heap Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "MB" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_heap_size_used_bytes{namespace=\"$namespace\",app_name=~\"$adapter.*\",app_name!=\"REFERENCE_TRANSFORM\"} / 1000 / 1000)"
    }
   ]
  },
  {
   "title": "Top 10 - Websocket Subscriptions",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(ws_connection_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (app_name))"
    }
   ]
  },
  {
   "title": "Top 10 - Websocket Subscriptions per second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "ops/s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(ws_subscription_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) by (app_name))"
    }
   ]
  },
  {
   "title": "Top 10 - Websocket Messages per second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(ws_connection_active{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (app_name))"
    }
   ]
  },
  {
   "title": "Top 10 - Websocket Errors per second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(ws_subscription_errors{namespace=\"$namespace\",app_name=~\"$adapter.*\"}[$__rate_interval])) by (app_name))"
    }
   ]
  },
  {
   "title": "Top 10 - Cache Warmer Subscriptions",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(cache_warmer_get_count{namespace=\"$namespace\",app_name=~\"$adapter.*\"}) by (app_name))"
    }
   ]
  },
  {
   "title": "Cache Warmer Requests Error Rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\",is_cache_warming=\"true\",provider_status_code!=\"undefined\",provider_status_code!=\"200\"}[$__rate_interval])) by (app_name) / sum(rate(http_requests_total{namespace=\"$namespace\",app_name=~\"$adapter.*\",is_cache_warming=\"true\"}[$__rate_interval])) by (app_name) * 100"
    }
   ]
  }
 ]
}